name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Run tests with coverage
      run: make coverage GOTEST_FLAGS="-covermode=atomic"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./.tmp/coverage/coverage_*.out
        flags: unittests
        name: codecov-slog
        fail_ci_if_error: true
        codecov_yml_path: ./.tmp/coverage/codecov.yml
