name: Test and Coverage

on:
  push:
    branches-ignore:
      - '**-wip'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true

    - name: Run tests with coverage
      run: make coverage GOTEST_FLAGS="-covermode=atomic"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./.tmp/coverage/coverage.out
        disable_search: true
        fail_ci_if_error: true
        codecov_yml_path: ./.tmp/coverage/codecov.yml
